<a href="https://colab.research.google.com/github/DeelakaGunasinghe/Machine-learning/blob/main/MLCW_Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
import csv

In [3]:
dataset = pd.read_csv('spambase.data')

In [4]:
dataset

,0,0.64,0.64.1,0.1,0.32,0.2,0.3,0.4,0.5,0.6,...,0.41,0.42,0.43,0.778,0.44,0.45,3.756,61,278,1
0,0.21,0.28,0.50,0.0,0.14,0.28,0.21,0.07,0.00,0.94,...,0.000,0.132,0.0,0.372,0.180,0.048,5.114,101,1028,1
1,0.06,0.00,0.71,0.0,1.23,0.19,0.19,0.12,0.64,0.25,...,0.010,0.143,0.0,0.276,0.184,0.010,9.821,485,2259,1
2,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.000,0.137,0.0,0.137,0.000,0.000,3.537,40,191,1
3,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.000,0.135,0.0,0.135,0.000,0.000,3.537,40,191,1
4,0.00,0.00,0.00,0.0,1.85,0.00,0.00,1.85,0.00,0.00,...,0.000,0.223,0.0,0.000,0.000,0.000,3.000,15,54,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4595,0.31,0.00,0.62,0.0,0.00,0.31,0.00,0.00,0.00,0.00,...,0.000,0.232,0.0,0.000,0.000,0.000,1.142,3,88,0
4596,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,...,0.000,0.000,0.0,0.353,0.000,0.000,1.555,4,14,0
4597,0.30,0.00,0.30,0.0,0.00,0.00,0.00,0.00,0.00,0.00,...,0.102,0.718,0.0,0.000,0.000,0.000,1.404,6,118,0
4598,0.96,0.00,0.00,0.0,0.32,0.00,0.00,0.00,0.00,0.00,...,0.000,0.057,0.0,0.000,0.000,0.000,1.147,5,78,0
4599,0.00,0.00,0.65,0.0,0.00,0.00,0.00,0.00,0.00,0.00,...,0.000,0.000,0.0,0.125,0.000,0.000,1.250,5,40,0

In [5]:
dataset.columns = ['word_freq_make','word_freq_address','word_freq_all','word_freq_3d','word_freq_our','word_freq_over','word_freq_remove','word_freq_internet','word_freq_order','word_freq_mail','word_freq_receive','word_freq_will','word_freq_people','word_freq_report','word_freq_addresses','word_freq_free','word_freq_business','word_freq_email','word_freq_you','word_freq_credit','word_freq_your','word_freq_font','word_freq_000','word_freq_money','word_freq_hp','word_freq_hpl','word_freq_george','word_freq_650','word_freq_lab','word_freq_labs','word_freq_telnet','word_freq_857','word_freq_data','word_freq_415','word_freq_85','word_freq_technology','word_freq_1999','word_freq_parts','word_freq_pm','word_freq_direct','word_freq_cs','word_freq_meeting','word_freq_original','word_freq_project','word_freq_re','word_freq_edu','word_freq_table','word_freq_conference','char_freq_;','char_freq_(','char_freq_[','char_freq_!','char_freq_$','char_freq_#','capital_run_length_average','capital_run_length_longest','capital_run_length_total','class']
dataset

,word_freq_make,word_freq_address,word_freq_all,word_freq_3d,word_freq_our,word_freq_over,word_freq_remove,word_freq_internet,word_freq_order,word_freq_mail,...,char_freq_;,char_freq_(,char_freq_[,char_freq_!,char_freq_$,char_freq_#,capital_run_length_average,capital_run_length_longest,capital_run_length_total,class
0,0.21,0.28,0.50,0.0,0.14,0.28,0.21,0.07,0.00,0.94,...,0.000,0.132,0.0,0.372,0.180,0.048,5.114,101,1028,1
1,0.06,0.00,0.71,0.0,1.23,0.19,0.19,0.12,0.64,0.25,...,0.010,0.143,0.0,0.276,0.184,0.010,9.821,485,2259,1
2,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.000,0.137,0.0,0.137,0.000,0.000,3.537,40,191,1
3,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.000,0.135,0.0,0.135,0.000,0.000,3.537,40,191,1
4,0.00,0.00,0.00,0.0,1.85,0.00,0.00,1.85,0.00,0.00,...,0.000,0.223,0.0,0.000,0.000,0.000,3.000,15,54,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4595,0.31,0.00,0.62,0.0,0.00,0.31,0.00,0.00,0.00,0.00,...,0.000,0.232,0.0,0.000,0.000,0.000,1.142,3,88,0
4596,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,...,0.000,0.000,0.0,0.353,0.000,0.000,1.555,4,14,0
4597,0.30,0.00,0.30,0.0,0.00,0.00,0.00,0.00,0.00,0.00,...,0.102,0.718,0.0,0.000,0.000,0.000,1.404,6,118,0
4598,0.96,0.00,0.00,0.0,0.32,0.00,0.00,0.00,0.00,0.00,...,0.000,0.057,0.0,0.000,0.000,0.000,1.147,5,78,0
4599,0.00,0.00,0.65,0.0,0.00,0.00,0.00,0.00,0.00,0.00,...,0.000,0.000,0.0,0.125,0.000,0.000,1.250,5,40,0

In [6]:
dataset.head()

,word_freq_make,word_freq_address,word_freq_all,word_freq_3d,word_freq_our,word_freq_over,word_freq_remove,word_freq_internet,word_freq_order,word_freq_mail,...,char_freq_;,char_freq_(,char_freq_[,char_freq_!,char_freq_$,char_freq_#,capital_run_length_average,capital_run_length_longest,capital_run_length_total,class
0,0.21,0.28,0.50,0.0,0.14,0.28,0.21,0.07,0.00,0.94,...,0.00,0.132,0.0,0.372,0.180,0.048,5.114,101,1028,1
1,0.06,0.00,0.71,0.0,1.23,0.19,0.19,0.12,0.64,0.25,...,0.01,0.143,0.0,0.276,0.184,0.010,9.821,485,2259,1
2,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.00,0.137,0.0,0.137,0.000,0.000,3.537,40,191,1
3,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.00,0.135,0.0,0.135,0.000,0.000,3.537,40,191,1
4,0.00,0.00,0.00,0.0,1.85,0.00,0.00,1.85,0.00,0.00,...,0.00,0.223,0.0,0.000,0.000,0.000,3.000,15,54,1

In [7]:
dataset.shape

(4600, 58)

In [8]:
remove_class_column = dataset.drop(columns=['class'])

In [9]:
remove_class_column.head()

,word_freq_make,word_freq_address,word_freq_all,word_freq_3d,word_freq_our,word_freq_over,word_freq_remove,word_freq_internet,word_freq_order,word_freq_mail,...,word_freq_conference,char_freq_;,char_freq_(,char_freq_[,char_freq_!,char_freq_$,char_freq_#,capital_run_length_average,capital_run_length_longest,capital_run_length_total
0,0.21,0.28,0.50,0.0,0.14,0.28,0.21,0.07,0.00,0.94,...,0.0,0.00,0.132,0.0,0.372,0.180,0.048,5.114,101,1028
1,0.06,0.00,0.71,0.0,1.23,0.19,0.19,0.12,0.64,0.25,...,0.0,0.01,0.143,0.0,0.276,0.184,0.010,9.821,485,2259
2,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.0,0.00,0.137,0.0,0.137,0.000,0.000,3.537,40,191
3,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.0,0.00,0.135,0.0,0.135,0.000,0.000,3.537,40,191
4,0.00,0.00,0.00,0.0,1.85,0.00,0.00,1.85,0.00,0.00,...,0.0,0.00,0.223,0.0,0.000,0.000,0.000,3.000,15,54

In [10]:
class_column = dataset['class'].values

class_column[0:5]

array([1, 1, 1, 1, 1])

In [11]:
x_train, x_test, y_train, y_test = train_test_split(remove_class_column,class_column, test_size=0.2, random_state=42)
print(f"X Training: {x_train}\n X Test: {x_test}\n Y Train: {y_train}\n Y Test: {y_test}")

X Training:       word_freq_make  word_freq_address  word_freq_all  word_freq_3d  \
1898            0.00               0.00           0.00           0.0
1370            0.00               0.00           0.00           0.0
3038            0.00               0.00           0.00           0.0
2361            0.00               0.00           0.00           0.0
156             0.00               0.00           0.00           0.0
...              ...                ...            ...           ...
4426            0.00               0.00           0.00           0.0
466             0.09               0.18           0.36           0.0
3092            0.00              14.28           0.00           0.0
3772            0.00               0.00           0.00           0.0
860             0.14               0.00           0.28           0.0

      word_freq_our  word_freq_over  word_freq_remove  word_freq_internet  \
1898           0.00            0.00              0.00                0.00
1370           0.00            0.00              0.00                1.11
3038           0.00            0.00              0.00                0.00
2361           0.00            0.00              0.00                0.00
156            1.36            0.45              0.45                0.00
...             ...             ...               ...                 ...
4426           0.00            0.00              0.00                0.00
466            0.09            0.00              0.09                0.00
3092           0.00            0.00              0.00                0.00
3772           1.23            0.00              0.00                0.00
860            0.09            0.24              0.04                0.04

      word_freq_order  word_freq_mail  ...  word_freq_conference  char_freq_;  \
1898             0.00            0.00  ...                   0.0          0.0
1370             0.00            0.00  ...                   0.0          0.0
3038             0.00            0.00  ...                   0.0          0.0
2361             0.00            0.00  ...                   0.0          0.0
156              0.00            0.00  ...                   0.0          0.0
...               ...             ...  ...                   ...          ...
4426             0.00            0.00  ...                   0.0          0.0
466              0.55            0.27  ...                   0.0          0.0
3092             0.00            0.00  ...                   0.0          0.0
3772             0.00            0.00  ...                   0.0          0.0
860              0.24            0.00  ...                   0.0          0.0

      char_freq_(  char_freq_[  char_freq_!  char_freq_$  char_freq_#  \
1898        0.000          0.0        0.000        0.000          0.0
1370        0.208          0.0        0.208        0.416          0.0
3038        0.000          0.0        0.000        0.000          0.0
2361        0.000          0.0        0.000        0.000          0.0
156         0.135          0.0        0.135        0.000          0.0
...           ...          ...          ...          ...          ...
4426        0.000          0.0        0.000        0.000          0.0
466         0.056          0.0        0.341        0.085          0.0
3092        0.000          0.0        0.000        0.000          0.0
3772        0.468          0.0        0.000        0.000          0.0
860         0.061          0.0        0.007        0.099          0.0

      capital_run_length_average  capital_run_length_longest  \
1898                       5.500                          10
1370                       3.950                          23
3038                       1.526                           7
2361                       4.228                          53
156                        5.571                          46
...                          ...                         ...
4426                       5.153                          55
466                        7.273                         103
3092                       1.800                           5
3772                       1.058                           2
860                        1.867                          14

      capital_run_length_total
1898                        11
1370                        79
3038                        87
2361                       148
156                        117
...                        ...
4426                        67
466                       1171
3092                         9
3772                        18
860                        521

[3680 rows x 57 columns]
 X Test:       word_freq_make  word_freq_address  word_freq_all  word_freq_3d  \
3683            0.00               0.00           0.00           0.0
4411            0.71               0.00           0.71           0.0
2584            0.00               0.00           1.09           0.0
69              0.00               0.00           0.00           0.0
1844            0.00               0.00           0.75           0.0
...              ...                ...            ...           ...
1612            0.14               0.29           0.44           0.0
1068            0.09               0.49           0.59           0.0
4350            0.00               0.00           0.00           0.0
3027            0.00               0.00           0.56           0.0
3455            0.00               0.00           0.00           0.0

      word_freq_our  word_freq_over  word_freq_remove  word_freq_internet  \
3683           0.00            0.00              0.00                0.00
4411           0.00            0.00              0.00                0.00
2584           0.00            0.00              0.00                0.00
69             1.26            0.00              2.53                1.26
1844           0.00            0.00              0.00                0.00
...             ...             ...               ...                 ...
1612           0.88            0.29              0.00                0.00
1068           0.39            0.19              0.00                0.00
4350           0.00            0.00              0.00                0.00
3027           0.00            0.00              0.00                0.00
3455           0.00            0.00              0.00                0.00

      word_freq_order  word_freq_mail  ...  word_freq_conference  char_freq_;  \
3683             0.00            0.00  ...                   0.0        0.000
4411             0.00            0.71  ...                   0.0        0.000
2584             0.00            1.09  ...                   0.0        0.000
69               1.26            1.26  ...                   0.0        0.000
1844             0.00            0.00  ...                   0.0        0.000
...               ...             ...  ...                   ...          ...
1612             1.47            1.47  ...                   0.0        0.000
1068             0.09            0.39  ...                   0.0        0.778
4350             0.00            0.00  ...                   0.0        0.000
3027             0.00            1.12  ...                   0.0        0.000
3455             0.00            0.00  ...                   0.0        0.000

      char_freq_(  char_freq_[  char_freq_!  char_freq_$  char_freq_#  \
3683        0.000          0.0        0.000        0.000        0.000
4411        0.000          0.0        0.000        0.000        0.000
2584        0.325          0.0        0.000        0.000        0.000
69          0.000          0.0        0.537        0.000        0.000
1844        0.262          0.0        0.000        0.000        0.000
...           ...          ...          ...          ...          ...
1612        0.023          0.0        1.004        0.215        0.047
1068        0.037          0.0        5.213        0.979        0.000
4350        0.000          0.0        0.000        0.000        0.000
3027        0.311          0.0        0.000        0.000        0.000
3455        0.000          0.0        0.000        0.000        0.000

      capital_run_length_average  capital_run_length_longest  \
3683                       1.000                           1
4411                       1.032                           2
2584                       4.586                          51
69                        72.500                         287
1844                       1.437                           3
...                          ...                         ...
1612                       6.602                         217
1068                       5.781                          54
4350                       1.000                           1
3027                       2.486                          11
3455                       1.611                           7

      capital_run_length_total
3683                         3
4411                        32
2584                       133
69                         290
1844                        23
...                        ...
1612                       898
1068                       740
4350                         3
3027                        92
3455                        29

[920 rows x 57 columns]
 Y Train: [0 1 0 ... 0 0 1]
 Y Test: [0 0 0 1 0 1 0 0 0 0 0 0 0 1 1 0 1 1 1 0 0 1 1 0 1 0 1 0 1 1 1 1 0 0 0 0 1
 1 0 1 1 0 0 0 1 1 1 0 1 1 1 0 0 1 0 0 0 0 0 0 1 0 1 1 1 0 0 0 1 0 0 0 0 1
 1 0 0 0 0 1 0 0 0 0 0 0 1 1 1 0 1 1 0 1 0 0 1 0 1 1 0 1 0 1 1 0 0 1 1 1 1
 1 1 0 1 1 0 0 0 0 1 0 1 0 1 0 0 0 1 0 0 1 1 0 0 0 1 0 1 1 1 1 0 0 1 1 0 0
 1 1 0 1 1 1 0 1 1 1 1 0 1 1 1 0 1 0 1 1 0 1 0 0 1 0 1 0 1 0 0 1 0 0 0 0 1
 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1
 1 1 1 0 1 0 0 0 0 0 0 0 1 0 0 0 1 1 0 1 1 1 0 0 0 1 0 0 0 1 0 0 0 1 1 1 1
 0 1 0 1 0 1 1 1 0 0 0 1 0 0 0 0 0 1 0 1 0 0 1 0 0 1 0 0 1 0 1 0 1 0 0 1 1
 0 0 0 0 0 1 0 0 0 0 1 1 1 0 1 0 1 1 0 1 0 1 1 1 0 0 0 0 0 1 1 1 1 0 0 0 1
 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 1 1 1 0 1 1 0 0 0 0 0 1 0
 1 1 0 1 0 0 0 0 1 0 1 1 1 0 1 0 1 0 0 1 0 0 1 1 0 1 0 1 0 0 1 0 0 0 1 1 0
 1 1 1 0 1 1 0 0 1 0 0 0 0 0 1 0 0 0 0 1 1 0 1 1 1 0 0 1 0 0 0 1 0 0 0 1 1
 0 1 0 0 0 1 0 0 0 1 0 0 1 1 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 0 0 1 0 0 0 1
 0 1 1 1 0 0 0 0 0 1 1 1 0 1 0 0 1 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 0
 0 1 0 1 0 0 1 0 0 0 1 0 0 0 0 1 1 0 1 1 1 0 1 0 0 0 1 1 1 1 1 1 0 0 1 0 1
 0 0 0 0 0 1 0 1 0 0 1 1 0 0 1 1 0 0 1 0 1 1 1 1 0 0 0 1 0 1 0 0 1 0 1 0 1
 1 1 0 1 0 0 0 1 1 1 1 0 1 1 0 1 0 0 1 0 0 0 1 0 0 0 0 1 1 1 0 1 0 0 1 1 0
 1 1 1 0 0 0 1 0 1 0 0 0 0 0 0 1 0 1 0 0 1 1 1 0 1 0 0 0 1 0 1 0 1 1 0 0 0
 1 1 0 0 1 1 0 1 0 1 0 1 0 1 0 1 1 1 0 0 0 0 1 1 0 0 1 0 0 0 1 0 1 0 0 0 0
 1 0 0 1 0 0 1 0 0 1 0 1 0 1 1 1 0 0 1 0 0 0 1 1 0 0 1 0 0 1 0 0 0 0 0 0 0
 0 1 1 0 0 1 0 0 0 1 1 1 0 0 0 1 0 1 0 1 1 1 1 0 1 0 0 1 0 0 0 0 0 0 1 0 0
 0 0 1 1 1 1 0 1 0 1 1 0 0 1 1 0 1 1 0 0 0 0 0 0 0 1 0 0 1 1 0 0 1 0 1 0 1
 0 0 1 0 0 0 0 0 1 0 1 1 0 1 1 0 0 1 0 0 0 0 0 0 0 1 1 1 0 1 1 0 1 1 1 0 0
 1 1 0 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 1 0 0 1 0 0 0
 0 0 1 1 1 1 1 0 0 0 0 0 0 1 0 1 0 1 0 1 0 0 0 0 0 0 1 1 1 0 0 0]